### ISSUE TITLE
write copy re: tips & guidelines for leading projects

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#14] opened 2017-10-12 18:13 UTC
resources on how to encourage remote collaboration, etc...

**Comment by JosephMcArthur** [comment] 2017-10-19 08:12
not needed for the OC so moving this back a bit

**Comment by JosephMcArthur** [comment] 2017-10-19 09:16
ohh, this is a duplicate of #33

**Closed as completed by JosephMcArthur** 2017-10-19 09:16 UTC
